In [1]:
import pandas as pd 
import datetime

In [22]:

def zero_pad_dataframe(df, num_pad_rows):
    # Create a DataFrame with the desired number of rows filled with zeros
    zero_pad_data = {
        col: [0] * num_pad_rows for col in df.columns
    }
    zero_pad_df = pd.DataFrame(zero_pad_data)

    # Concatenate the zero pad DataFrame before and after the original DataFrame
    final_df = pd.concat([zero_pad_df, df, zero_pad_df], ignore_index=True)
    
    return final_df

# Sample dataframe with 3 columns and 5 rows
data = {
    'col1': [1, 2, 3, 4, 5],
    'col2': [10, 20, 30, 40, 50],
    'col3': [100, 200, 300, 400, 500]
}

df = pd.DataFrame(data)

# Number of additional rows to add on both sides
num_pad_rows = 2

# Zero-pad the dataframe
padded_df = zero_pad_dataframe(df, num_pad_rows)
    

print(padded_df)

   col1  col2  col3
0     0     0     0
1     0     0     0
2     1    10   100
3     2    20   200
4     3    30   300
5     4    40   400
6     5    50   500
7     0     0     0
8     0     0     0


In [23]:
df = pd.DataFrame(
    {
        "col1": [1,2,3,4,5],
        "col2": [1,2,3,4,5]
    }
)
print(df)

df["index_ref"] = df.index

idx = 2

df = df[df.col1 != 2].reset_index(drop=True)
print(df)

idx_filtered = df[df["index_ref"] == idx].index.values[0]
print("Reset index: ", idx_filtered)

df_w = df.iloc[idx_filtered-1:idx_filtered+1+1]
print(df_w)

   col1  col2
0     1     1
1     2     2
2     3     3
3     4     4
4     5     5
   col1  col2  index_ref
0     1     1          0
1     3     3          2
2     4     4          3
3     5     5          4
Reset index:  1
   col1  col2  index_ref
0     1     1          0
1     3     3          2
2     4     4          3


# Explore Embbeding

In [45]:
import torch
import torch.nn as nn
import sys 

# Embedding Layer: 
emb = nn.Embedding(num_embeddings=6, embedding_dim=1)

print(emb.weight)


input = torch.LongTensor([[1,3], [5,5]])
print(input)

emb(input)

Parameter containing:
tensor([[ 0.4918],
        [ 1.7749],
        [-0.7107],
        [-0.0392],
        [-0.4191],
        [ 1.0474]], requires_grad=True)
tensor([[1, 3],
        [5, 5]])


tensor([[[ 1.7749],
         [-0.0392]],

        [[ 1.0474],
         [ 1.0474]]], grad_fn=<EmbeddingBackward0>)

In [29]:
df = pd.read_csv("/Users/wannerje/Documents/Digital-Assist-AI/In-Car-RecSys/Processed_data_new/01_Mf4_Extracted/SEB880_extracted_mf4.csv")
#df_parquet = pd.read_parquet(mf4_path)

In [30]:
counter = 0
for row in df.temperature_out:
    if row == "Init":
        counter += 1

print((counter))

0


In [47]:
import torch
import math
import sys 


a = torch.arange(0,10).unsqueeze(1).expand(10,3)
a = torch.arange(0,10).expand(4,10)

seq_len, hidden_dim = (5, 10)

pe = torch.zeros(seq_len, hidden_dim) # positional encoding 
pos = torch.arange(0, seq_len, dtype=torch.float32).unsqueeze(1)
_2i = torch.arange(0, hidden_dim, step=2).float()
pe[:, 0::2] = torch.sin(pos / (10000 ** (_2i / hidden_dim)))
pe[:, 1::2] = torch.cos(pos / (10000 ** (_2i / hidden_dim)))

print(pe)



tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  1.5783e-01,  9.8747e-01,  2.5116e-02,
          9.9968e-01,  3.9811e-03,  9.9999e-01,  6.3096e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  3.1170e-01,  9.5018e-01,  5.0217e-02,
          9.9874e-01,  7.9621e-03,  9.9997e-01,  1.2619e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  4.5775e-01,  8.8908e-01,  7.5285e-02,
          9.9716e-01,  1.1943e-02,  9.9993e-01,  1.8929e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  5.9234e-01,  8.0569e-01,  1.0031e-01,
          9.9496e-01,  1.5924e-02,  9.9987e-01,  2.5238e-03,  1.0000e+00]])


   education  color  age  target
0          1      2   25       0
1          0      0   30       1
2          2      1   28       1
3          0      2   22       0
4          1      0   35       1
6
tensor([[1, 0],
        [2, 1],
        [1, 2],
        [0, 2]])
torch.Size([4, 2])
torch.Size([4, 2, 8])


RuntimeError: Tensors must have same number of dimensions: got 3 and 2

In [65]:
from torchmetrics import Precision, F1Score, Recall, ConfusionMatrix, Accuracy

pred = torch.Tensor([0,1,2,0])
target = torch.Tensor([0,0,2,0])

acc = Accuracy(task="multiclass", num_classes=3)
f1 = F1Score(task="multiclass", average="macro", num_classes=3) 
precision = Precision(task="multiclass", average="macro", num_classes=3)
recall = Recall(task="multiclass", average="macro", num_classes=3)
confmat = ConfusionMatrix(task="multiclass", num_classes=3)
print(acc(pred, target))
print(f1(pred, target))
print(precision(pred, target))
print(recall(pred, target))
print(confmat(pred, target))


tensor(0.7500)
tensor(0.6000)
tensor(0.6667)
tensor(0.5556)
tensor([[2, 1, 0],
        [0, 0, 0],
        [0, 0, 1]])
